//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace Urban.Data
{
    /// <summary>
    ///     The DataContext manager class for the NateUrbanScheduler database.
    /// </summary>
    public partial class UrbanDataContext
    {
        private UrbanDataManager _manager;

        /// <summary>
        ///     Gets the data manager.
        /// </summary>
        /// <value>The data manager.</value>
        public UrbanDataManager Manager
        {
            get
            {
                if (_manager == null)
                    _manager = new UrbanDataManager(this);
                return _manager;
            }
        }
    }
}