#pragma warning disable 1591
#pragma warning disable 0414        
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Linq;

namespace Urban.Data
{
    /// <summary>
    /// The class representing the dbo.RoomImageLink table.
    /// </summary>
    [System.Data.Linq.Mapping.Table(Name="dbo.RoomImageLink")]
    [System.Runtime.Serialization.DataContract(IsReference = true)]
    [System.ComponentModel.DataAnnotations.ScaffoldTable(true)]
    [System.ComponentModel.DataAnnotations.MetadataType(typeof(Urban.Data.RoomImageLink.Metadata))]
    [System.Data.Services.Common.DataServiceKey("Id")]
    [System.Diagnostics.DebuggerDisplay("Id: {Id}")]
    public partial class RoomImageLink
        : LinqEntityBase, ICloneable 
    {
        #region Static Constructor
        /// <summary>
        /// Initializes the <see cref="RoomImageLink"/> class.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        static RoomImageLink()
        {
            AddSharedRules();
        }
        #endregion

        #region Default Constructor
        /// <summary>
        /// Initializes a new instance of the <see cref="RoomImageLink"/> class.
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCode]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public RoomImageLink()
        {
            Initialize();
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private void Initialize()
        {
            _fileFiles = default(System.Data.Linq.EntityRef<Files>);
            _room = default(System.Data.Linq.EntityRef<Room>);
            _roomImageType1 = default(System.Data.Linq.EntityRef<RoomImageType>);
            OnCreated();
        }
        #endregion

        #region Column Mapped Properties

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private int _id = default(int);

        /// <summary>
        /// Gets the ID column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "ID", Storage = "_id", DbType = "int NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true, CanBeNull = false)]
        [System.Runtime.Serialization.DataMember(Order = 1)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public int Id
        {
            get { return _id; }
            set
            {
                if (_id != value)
                {
                    OnIdChanging(value);
                    SendPropertyChanging("Id");
                    _id = value;
                    SendPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private int _fileID;

        /// <summary>
        /// Gets or sets the FileID column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "FileID", Storage = "_fileID", DbType = "int NOT NULL", CanBeNull = false)]
        [System.Runtime.Serialization.DataMember(Order = 2)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public int FileID
        {
            get { return _fileID; }
            set
            {
                if (_fileID != value)
                {
                    if (_fileFiles.HasLoadedOrAssignedValue)
                    {
                        throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
                    }
                    OnFileIDChanging(value);
                    SendPropertyChanging("FileID");
                    _fileID = value;
                    SendPropertyChanged("FileID");
                    OnFileIDChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private int _roomID;

        /// <summary>
        /// Gets or sets the RoomID column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "RoomID", Storage = "_roomID", DbType = "int NOT NULL", CanBeNull = false)]
        [System.Runtime.Serialization.DataMember(Order = 3)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public int RoomID
        {
            get { return _roomID; }
            set
            {
                if (_roomID != value)
                {
                    if (_room.HasLoadedOrAssignedValue)
                    {
                        throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
                    }
                    OnRoomIDChanging(value);
                    SendPropertyChanging("RoomID");
                    _roomID = value;
                    SendPropertyChanged("RoomID");
                    OnRoomIDChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private int _roomImageType;

        /// <summary>
        /// Gets or sets the RoomImageType column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "RoomImageType", Storage = "_roomImageType", DbType = "int NOT NULL", CanBeNull = false)]
        [System.Runtime.Serialization.DataMember(Order = 4)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public int RoomImageType
        {
            get { return _roomImageType; }
            set
            {
                if (_roomImageType != value)
                {
                    if (_roomImageType1.HasLoadedOrAssignedValue)
                    {
                        throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
                    }
                    OnRoomImageTypeChanging(value);
                    SendPropertyChanging("RoomImageType");
                    _roomImageType = value;
                    SendPropertyChanged("RoomImageType");
                    OnRoomImageTypeChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private string _title;

        /// <summary>
        /// Gets or sets the Title column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "Title", Storage = "_title", DbType = "nvarchar(150)")]
        [System.ComponentModel.DataAnnotations.StringLength(150)]
        [System.Runtime.Serialization.DataMember(Order = 5)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public string Title
        {
            get { return _title; }
            set
            {
                if (_title != value)
                {
                    OnTitleChanging(value);
                    SendPropertyChanging("Title");
                    _title = value;
                    SendPropertyChanged("Title");
                    OnTitleChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private string _imageDescription;

        /// <summary>
        /// Gets or sets the ImageDescription column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "ImageDescription", Storage = "_imageDescription", DbType = "nvarchar(MAX)")]
        [System.Runtime.Serialization.DataMember(Order = 6)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public string ImageDescription
        {
            get { return _imageDescription; }
            set
            {
                if (_imageDescription != value)
                {
                    OnImageDescriptionChanging(value);
                    SendPropertyChanging("ImageDescription");
                    _imageDescription = value;
                    SendPropertyChanged("ImageDescription");
                    OnImageDescriptionChanged();
                }
            }
        }
        #endregion

        #region Association Mapped Properties

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.Data.Linq.EntityRef<Files> _fileFiles;

        /// <summary>
        /// Gets or sets the <see cref="Files"/> association.
        /// </summary>
        [System.Data.Linq.Mapping.Association(Name = "Files_RoomImageLink", Storage = "_fileFiles", ThisKey = "FileID", OtherKey = "Id", IsForeignKey = true)]
        [System.Runtime.Serialization.DataMember(Order = 7, EmitDefaultValue = false)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public Files FileFiles
        {
            get { return (serializing && !_fileFiles.HasLoadedOrAssignedValue) ? null : _fileFiles.Entity; }
            set
            {
                Files previousValue = _fileFiles.Entity;
                if (previousValue != value || _fileFiles.HasLoadedOrAssignedValue == false)
                {
                    OnFileFilesChanging(value);
                    SendPropertyChanging("FileFiles");
                    if (previousValue != null)
                    {
                        _fileFiles.Entity = null;
                        previousValue.FileRoomImageLinkList.Remove(this);
                    }
                    _fileFiles.Entity = value;
                    if (value != null)
                    {
                        value.FileRoomImageLinkList.Add(this);
                        _fileID = value.Id;
                    }
                    else
                    {
                        _fileID = default(int);
                    }
                    SendPropertyChanged("FileFiles");
                    OnFileFilesChanged();
                }
            }
        }
        
        
        

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.Data.Linq.EntityRef<Room> _room;

        /// <summary>
        /// Gets or sets the <see cref="Room"/> association.
        /// </summary>
        [System.Data.Linq.Mapping.Association(Name = "Room_RoomImageLink", Storage = "_room", ThisKey = "RoomID", OtherKey = "Id", IsForeignKey = true)]
        [System.Runtime.Serialization.DataMember(Order = 8, EmitDefaultValue = false)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public Room Room
        {
            get { return (serializing && !_room.HasLoadedOrAssignedValue) ? null : _room.Entity; }
            set
            {
                Room previousValue = _room.Entity;
                if (previousValue != value || _room.HasLoadedOrAssignedValue == false)
                {
                    OnRoomChanging(value);
                    SendPropertyChanging("Room");
                    if (previousValue != null)
                    {
                        _room.Entity = null;
                        previousValue.RoomImageLinkList.Remove(this);
                    }
                    _room.Entity = value;
                    if (value != null)
                    {
                        value.RoomImageLinkList.Add(this);
                        _roomID = value.Id;
                    }
                    else
                    {
                        _roomID = default(int);
                    }
                    SendPropertyChanged("Room");
                    OnRoomChanged();
                }
            }
        }
        
        
        

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.Data.Linq.EntityRef<RoomImageType> _roomImageType1;

        /// <summary>
        /// Gets or sets the <see cref="RoomImageType"/> association.
        /// </summary>
        [System.Data.Linq.Mapping.Association(Name = "RoomImageType_RoomImageLink", Storage = "_roomImageType1", ThisKey = "RoomImageType", OtherKey = "Id", IsForeignKey = true)]
        [System.Runtime.Serialization.DataMember(Order = 9, EmitDefaultValue = false)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public RoomImageType RoomImageType1
        {
            get { return (serializing && !_roomImageType1.HasLoadedOrAssignedValue) ? null : _roomImageType1.Entity; }
            set
            {
                RoomImageType previousValue = _roomImageType1.Entity;
                if (previousValue != value || _roomImageType1.HasLoadedOrAssignedValue == false)
                {
                    OnRoomImageType1Changing(value);
                    SendPropertyChanging("RoomImageType1");
                    if (previousValue != null)
                    {
                        _roomImageType1.Entity = null;
                        previousValue.RoomImageLinkList.Remove(this);
                    }
                    _roomImageType1.Entity = value;
                    if (value != null)
                    {
                        value.RoomImageLinkList.Add(this);
                        _roomImageType = value.Id;
                    }
                    else
                    {
                        _roomImageType = default(int);
                    }
                    SendPropertyChanged("RoomImageType1");
                    OnRoomImageType1Changed();
                }
            }
        }
        
        
        
        #endregion

        #region Extensibility Method Definitions
        /// <summary>Called by the static constructor to add shared rules.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        static partial void AddSharedRules();
        /// <summary>Called when this instance is loaded.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnLoaded();
        /// <summary>Called when this instance is being saved.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        /// <summary>Called when this instance is created.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnCreated();
        /// <summary>Called when <see cref="Id"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnIdChanging(int value);
        /// <summary>Called after <see cref="Id"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnIdChanged();
        /// <summary>Called when <see cref="FileID"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnFileIDChanging(int value);
        /// <summary>Called after <see cref="FileID"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnFileIDChanged();
        /// <summary>Called when <see cref="RoomID"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnRoomIDChanging(int value);
        /// <summary>Called after <see cref="RoomID"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnRoomIDChanged();
        /// <summary>Called when <see cref="RoomImageType"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnRoomImageTypeChanging(int value);
        /// <summary>Called after <see cref="RoomImageType"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnRoomImageTypeChanged();
        /// <summary>Called when <see cref="Title"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnTitleChanging(string value);
        /// <summary>Called after <see cref="Title"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnTitleChanged();
        /// <summary>Called when <see cref="ImageDescription"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnImageDescriptionChanging(string value);
        /// <summary>Called after <see cref="ImageDescription"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnImageDescriptionChanged();
        /// <summary>Called when <see cref="FileFiles"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnFileFilesChanging(Files value);
        /// <summary>Called after <see cref="FileFiles"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnFileFilesChanged();
        /// <summary>Called when <see cref="Room"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnRoomChanging(Room value);
        /// <summary>Called after <see cref="Room"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnRoomChanged();
        /// <summary>Called when <see cref="RoomImageType1"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnRoomImageType1Changing(RoomImageType value);
        /// <summary>Called after <see cref="RoomImageType1"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnRoomImageType1Changed();

        #endregion

        #region Serialization
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private bool serializing;

        /// <summary>
        /// Called when serializing.
        /// </summary>
        /// <param name="context">The <see cref="System.Runtime.Serialization.StreamingContext"/> for the serialization.</param>
        [System.Runtime.Serialization.OnSerializing]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public void OnSerializing(System.Runtime.Serialization.StreamingContext context) {
            serializing = true;
        }

        /// <summary>
        /// Called when serialized.
        /// </summary>
        /// <param name="context">The <see cref="System.Runtime.Serialization.StreamingContext"/> for the serialization.</param>
        [System.Runtime.Serialization.OnSerialized]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public void OnSerialized(System.Runtime.Serialization.StreamingContext context) {
            serializing = false;
        }

        /// <summary>
        /// Called when deserializing.
        /// </summary>
        /// <param name="context">The <see cref="System.Runtime.Serialization.StreamingContext"/> for the serialization.</param>
        [System.Runtime.Serialization.OnDeserializing]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public void OnDeserializing(System.Runtime.Serialization.StreamingContext context) {
            Initialize();
        }

        /// <summary>
        /// Deserializes an instance of <see cref="RoomImageLink"/> from XML.
        /// </summary>
        /// <param name="xml">The XML string representing a <see cref="RoomImageLink"/> instance.</param>
        /// <returns>An instance of <see cref="RoomImageLink"/> that is deserialized from the XML string.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public static RoomImageLink FromXml(string xml)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(RoomImageLink));

            using (var sr = new System.IO.StringReader(xml))
            using (var reader = System.Xml.XmlReader.Create(sr))
            {
                return deserializer.ReadObject(reader) as RoomImageLink;
            }
        }

        /// <summary>
        /// Deserializes an instance of <see cref="RoomImageLink"/> from a byte array.
        /// </summary>
        /// <param name="buffer">The byte array representing a <see cref="RoomImageLink"/> instance.</param>
        /// <returns>An instance of <see cref="RoomImageLink"/> that is deserialized from the byte array.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public static RoomImageLink FromBinary(byte[] buffer)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(RoomImageLink));

            using (var ms = new System.IO.MemoryStream(buffer))
            using (var reader = System.Xml.XmlDictionaryReader.CreateBinaryReader(ms, System.Xml.XmlDictionaryReaderQuotas.Max))
            {
                return deserializer.ReadObject(reader) as RoomImageLink;
            }
        }
        
        #endregion

        #region Clone
        /// <summary>
        /// Creates a new object that is a copy of the current instance.
        /// </summary>
        /// <returns>
        /// A new object that is a copy of this instance.
        /// </returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        object ICloneable.Clone()
        {
            var serializer = new System.Runtime.Serialization.DataContractSerializer(GetType());
            using (var ms = new System.IO.MemoryStream())
            {
                serializer.WriteObject(ms, this);
                ms.Position = 0;
                return serializer.ReadObject(ms);
            }
        }

        /// <summary>
        /// Creates a new object that is a copy of the current instance.
        /// </summary>
        /// <returns>
        /// A new object that is a copy of this instance.
        /// </returns>
        /// <remarks>
        /// Only loaded <see cref="T:System.Data.Linq.EntityRef`1"/> and <see cref="T:System.Data.Linq.EntitySet`1" /> child accessions will be cloned.
        /// </remarks>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public RoomImageLink Clone()
        {
            return (RoomImageLink)((ICloneable)this).Clone();
        }
        #endregion

        #region Detach Methods
        /// <summary>
        /// Detach this instance from the <see cref="System.Data.Linq.DataContext"/>.
        /// </summary>
        /// <remarks>
        /// Detaching the entity will stop all lazy loading and allow it to be added to another <see cref="System.Data.Linq.DataContext"/>.
        /// </remarks>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public override void Detach()
        {
            if (!IsAttached())
                return;

            base.Detach();
            _fileFiles = Detach(_fileFiles);
            _room = Detach(_room);
            _roomImageType1 = Detach(_roomImageType1);
        }
        #endregion
    }
}
#pragma warning restore 1591
#pragma warning restore 0414

