#pragma warning disable 1591
#pragma warning disable 0414        
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using Urban.Data;

namespace UrbanSchedulerProject.Entities
{
    /// <summary>
    /// The class representing the dbo.User table.
    /// </summary>
    [System.Data.Linq.Mapping.Table(Name="dbo.User")]
    [System.Runtime.Serialization.DataContract(IsReference = true)]
    [System.ComponentModel.DataAnnotations.ScaffoldTable(true)]
    [System.ComponentModel.DataAnnotations.MetadataType(typeof(User.Metadata))]
    [System.Data.Services.Common.DataServiceKey("Id")]
    [System.Diagnostics.DebuggerDisplay("Id: {Id}")]
    public partial class User
        : LinqEntityBase, ICloneable 
    {
        #region Static Constructor
        /// <summary>
        /// Initializes the <see cref="User"/> class.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        static User()
        {
            AddSharedRules();
        }
        #endregion

        #region Default Constructor
        /// <summary>
        /// Initializes a new instance of the <see cref="User"/> class.
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCode]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public User()
        {
            Initialize();
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private void Initialize()
        {
            _room = default(System.Data.Linq.EntityRef<Room>);
            _buildingList = new System.Data.Linq.EntitySet<Building>(OnBuildingListAdd, OnBuildingListRemove);
            _roomCommentsList = new System.Data.Linq.EntitySet<RoomComments>(OnRoomCommentsListAdd, OnRoomCommentsListRemove);
            _reserverRoomReservationList = new System.Data.Linq.EntitySet<RoomReservation>(OnReserverRoomReservationListAdd, OnReserverRoomReservationListRemove);
            _roomReservationCommentsList = new System.Data.Linq.EntitySet<RoomReservationComments>(OnRoomReservationCommentsListAdd, OnRoomReservationCommentsListRemove);
            OnCreated();
        }
        #endregion

        #region Column Mapped Properties

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private int _id = default(int);

        /// <summary>
        /// Gets the ID column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "ID", Storage = "_id", DbType = "int NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true, CanBeNull = false)]
        [System.Runtime.Serialization.DataMember(Order = 1)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public int Id
        {
            get { return _id; }
            set
            {
                if (_id != value)
                {
                    OnIdChanging(value);
                    SendPropertyChanging("Id");
                    _id = value;
                    SendPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private string _email;

        /// <summary>
        /// Gets or sets the Email column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "Email", Storage = "_email", DbType = "nvarchar(MAX) NOT NULL", CanBeNull = false)]
        [System.Runtime.Serialization.DataMember(Order = 2)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public string Email
        {
            get { return _email; }
            set
            {
                if (_email != value)
                {
                    OnEmailChanging(value);
                    SendPropertyChanging("Email");
                    _email = value;
                    SendPropertyChanged("Email");
                    OnEmailChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private Nullable<bool> _isUserAuthenticated;

        /// <summary>
        /// Gets or sets the IsUserAuthenticated column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "IsUserAuthenticated", Storage = "_isUserAuthenticated", DbType = "bit")]
        [System.Runtime.Serialization.DataMember(Order = 3)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public Nullable<bool> IsUserAuthenticated
        {
            get { return _isUserAuthenticated; }
            set
            {
                if (_isUserAuthenticated != value)
                {
                    OnIsUserAuthenticatedChanging(value);
                    SendPropertyChanging("IsUserAuthenticated");
                    _isUserAuthenticated = value;
                    SendPropertyChanged("IsUserAuthenticated");
                    OnIsUserAuthenticatedChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private bool _isAdmin;

        /// <summary>
        /// Gets or sets the IsAdmin column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "IsAdmin", Storage = "_isAdmin", DbType = "bit NOT NULL", CanBeNull = false)]
        [System.Runtime.Serialization.DataMember(Order = 4)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public bool IsAdmin
        {
            get { return _isAdmin; }
            set
            {
                if (_isAdmin != value)
                {
                    OnIsAdminChanging(value);
                    SendPropertyChanging("IsAdmin");
                    _isAdmin = value;
                    SendPropertyChanged("IsAdmin");
                    OnIsAdminChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private string _firstName;

        /// <summary>
        /// Gets or sets the FirstName column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "FirstName", Storage = "_firstName", DbType = "nvarchar(150)")]
        [System.ComponentModel.DataAnnotations.StringLength(150)]
        [System.Runtime.Serialization.DataMember(Order = 5)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public string FirstName
        {
            get { return _firstName; }
            set
            {
                if (_firstName != value)
                {
                    OnFirstNameChanging(value);
                    SendPropertyChanging("FirstName");
                    _firstName = value;
                    SendPropertyChanged("FirstName");
                    OnFirstNameChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private string _lastName;

        /// <summary>
        /// Gets or sets the LastName column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "LastName", Storage = "_lastName", DbType = "nvarchar(150)")]
        [System.ComponentModel.DataAnnotations.StringLength(150)]
        [System.Runtime.Serialization.DataMember(Order = 6)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public string LastName
        {
            get { return _lastName; }
            set
            {
                if (_lastName != value)
                {
                    OnLastNameChanging(value);
                    SendPropertyChanging("LastName");
                    _lastName = value;
                    SendPropertyChanged("LastName");
                    OnLastNameChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private string _phoneNumber;

        /// <summary>
        /// Gets or sets the PhoneNumber column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "PhoneNumber", Storage = "_phoneNumber", DbType = "nvarchar(150)")]
        [System.ComponentModel.DataAnnotations.StringLength(150)]
        [System.Runtime.Serialization.DataMember(Order = 7)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public string PhoneNumber
        {
            get { return _phoneNumber; }
            set
            {
                if (_phoneNumber != value)
                {
                    OnPhoneNumberChanging(value);
                    SendPropertyChanging("PhoneNumber");
                    _phoneNumber = value;
                    SendPropertyChanged("PhoneNumber");
                    OnPhoneNumberChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private string _primaryAddress;

        /// <summary>
        /// Gets or sets the PrimaryAddress column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "PrimaryAddress", Storage = "_primaryAddress", DbType = "nvarchar(150)")]
        [System.ComponentModel.DataAnnotations.StringLength(150)]
        [System.Runtime.Serialization.DataMember(Order = 8)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public string PrimaryAddress
        {
            get { return _primaryAddress; }
            set
            {
                if (_primaryAddress != value)
                {
                    OnPrimaryAddressChanging(value);
                    SendPropertyChanging("PrimaryAddress");
                    _primaryAddress = value;
                    SendPropertyChanged("PrimaryAddress");
                    OnPrimaryAddressChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private string _secondaryAddress;

        /// <summary>
        /// Gets or sets the SecondaryAddress column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "SecondaryAddress", Storage = "_secondaryAddress", DbType = "nvarchar(500)")]
        [System.ComponentModel.DataAnnotations.StringLength(500)]
        [System.Runtime.Serialization.DataMember(Order = 9)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public string SecondaryAddress
        {
            get { return _secondaryAddress; }
            set
            {
                if (_secondaryAddress != value)
                {
                    OnSecondaryAddressChanging(value);
                    SendPropertyChanging("SecondaryAddress");
                    _secondaryAddress = value;
                    SendPropertyChanged("SecondaryAddress");
                    OnSecondaryAddressChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private string _city;

        /// <summary>
        /// Gets or sets the City column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "City", Storage = "_city", DbType = "nvarchar(150)")]
        [System.ComponentModel.DataAnnotations.StringLength(150)]
        [System.Runtime.Serialization.DataMember(Order = 10)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public string City
        {
            get { return _city; }
            set
            {
                if (_city != value)
                {
                    OnCityChanging(value);
                    SendPropertyChanging("City");
                    _city = value;
                    SendPropertyChanged("City");
                    OnCityChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private string _zip;

        /// <summary>
        /// Gets or sets the Zip column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "Zip", Storage = "_zip", DbType = "nvarchar(150)")]
        [System.ComponentModel.DataAnnotations.StringLength(150)]
        [System.Runtime.Serialization.DataMember(Order = 11)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public string Zip
        {
            get { return _zip; }
            set
            {
                if (_zip != value)
                {
                    OnZipChanging(value);
                    SendPropertyChanging("Zip");
                    _zip = value;
                    SendPropertyChanged("Zip");
                    OnZipChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private string _userName;

        /// <summary>
        /// Gets or sets the UserName column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "UserName", Storage = "_userName", DbType = "nvarchar(150)")]
        [System.ComponentModel.DataAnnotations.StringLength(150)]
        [System.Runtime.Serialization.DataMember(Order = 12)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public string UserName
        {
            get { return _userName; }
            set
            {
                if (_userName != value)
                {
                    OnUserNameChanging(value);
                    SendPropertyChanging("UserName");
                    _userName = value;
                    SendPropertyChanged("UserName");
                    OnUserNameChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private string _password;

        /// <summary>
        /// Gets or sets the Password column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "Password", Storage = "_password", DbType = "nvarchar(200)")]
        [System.ComponentModel.DataAnnotations.StringLength(200)]
        [System.Runtime.Serialization.DataMember(Order = 13)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public string Password
        {
            get { return _password; }
            set
            {
                if (_password != value)
                {
                    OnPasswordChanging(value);
                    SendPropertyChanging("Password");
                    _password = value;
                    SendPropertyChanged("Password");
                    OnPasswordChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private string _passwordSalt;

        /// <summary>
        /// Gets or sets the PasswordSalt column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "PasswordSalt", Storage = "_passwordSalt", DbType = "nvarchar(200)")]
        [System.ComponentModel.DataAnnotations.StringLength(200)]
        [System.Runtime.Serialization.DataMember(Order = 14)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public string PasswordSalt
        {
            get { return _passwordSalt; }
            set
            {
                if (_passwordSalt != value)
                {
                    OnPasswordSaltChanging(value);
                    SendPropertyChanging("PasswordSalt");
                    _passwordSalt = value;
                    SendPropertyChanged("PasswordSalt");
                    OnPasswordSaltChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private Nullable<System.DateTime> _dateCreated;

        /// <summary>
        /// Gets or sets the DateCreated column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "DateCreated", Storage = "_dateCreated", DbType = "datetime")]
        [System.Runtime.Serialization.DataMember(Order = 15)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public Nullable<System.DateTime> DateCreated
        {
            get { return _dateCreated; }
            set
            {
                if (_dateCreated != value)
                {
                    OnDateCreatedChanging(value);
                    SendPropertyChanging("DateCreated");
                    _dateCreated = value;
                    SendPropertyChanged("DateCreated");
                    OnDateCreatedChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private Nullable<System.Guid> _activationGuid;

        /// <summary>
        /// Gets or sets the ActivationGuid column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "ActivationGuid", Storage = "_activationGuid", DbType = "uniqueidentifier")]
        [System.Runtime.Serialization.DataMember(Order = 16)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public Nullable<System.Guid> ActivationGuid
        {
            get { return _activationGuid; }
            set
            {
                if (_activationGuid != value)
                {
                    OnActivationGuidChanging(value);
                    SendPropertyChanging("ActivationGuid");
                    _activationGuid = value;
                    SendPropertyChanged("ActivationGuid");
                    OnActivationGuidChanged();
                }
            }
        }
        #endregion

        #region Association Mapped Properties

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.Data.Linq.EntityRef<Room> _room;

        /// <summary>
        /// Gets or sets the <see cref="Room"/> association.
        /// </summary>
        [System.Data.Linq.Mapping.Association(Name = "User_Room", Storage = "_room", ThisKey = "Id", OtherKey = "Id", IsUnique = true)]
        [System.Runtime.Serialization.DataMember(Order = 17, EmitDefaultValue = false)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public Room Room
        {
            get { return (serializing && !_room.HasLoadedOrAssignedValue) ? null : _room.Entity; }
            set
            {
                Room previousValue = _room.Entity;
                if (previousValue != value || _room.HasLoadedOrAssignedValue == false)
                {
                    OnRoomChanging(value);
                    SendPropertyChanging("Room");
                    if (previousValue != null)
                    {
                        _room.Entity = null;
                        previousValue.User = null;
                    }
                    _room.Entity = value;
                    if (value != null)
                    {
                        value.User = this;
                    }
                    SendPropertyChanged("Room");
                    OnRoomChanged();
                }
            }
        }
        
        
        

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.Data.Linq.EntitySet<Building> _buildingList;

        /// <summary>
        /// Gets or sets the <see cref="Building"/> association.
        /// </summary>
        [System.Data.Linq.Mapping.Association(Name = "User_Building", Storage = "_buildingList", ThisKey = "Id", OtherKey = "UserID")]
        [System.Runtime.Serialization.DataMember(Order=18, EmitDefaultValue=false)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public System.Data.Linq.EntitySet<Building> BuildingList
        {
            get { return (serializing && !_buildingList.HasLoadedOrAssignedValues) ? null : _buildingList; }
            set { _buildingList.Assign(value); }
        }
        
        

        [System.Diagnostics.DebuggerNonUserCode]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private void OnBuildingListAdd(Building entity)
        {
            SendPropertyChanging(null);
            entity.User = this;
            SendPropertyChanged(null);
        }

        [System.Diagnostics.DebuggerNonUserCode]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private void OnBuildingListRemove(Building entity)
        {
            SendPropertyChanging(null);
            entity.User = null;
            SendPropertyChanged(null);
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.Data.Linq.EntitySet<RoomComments> _roomCommentsList;

        /// <summary>
        /// Gets or sets the <see cref="RoomComments"/> association.
        /// </summary>
        [System.Data.Linq.Mapping.Association(Name = "User_RoomComments", Storage = "_roomCommentsList", ThisKey = "Id", OtherKey = "UserID")]
        [System.Runtime.Serialization.DataMember(Order=19, EmitDefaultValue=false)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public System.Data.Linq.EntitySet<RoomComments> RoomCommentsList
        {
            get { return (serializing && !_roomCommentsList.HasLoadedOrAssignedValues) ? null : _roomCommentsList; }
            set { _roomCommentsList.Assign(value); }
        }
        
        

        [System.Diagnostics.DebuggerNonUserCode]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private void OnRoomCommentsListAdd(RoomComments entity)
        {
            SendPropertyChanging(null);
            entity.User = this;
            SendPropertyChanged(null);
        }

        [System.Diagnostics.DebuggerNonUserCode]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private void OnRoomCommentsListRemove(RoomComments entity)
        {
            SendPropertyChanging(null);
            entity.User = null;
            SendPropertyChanged(null);
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.Data.Linq.EntitySet<RoomReservation> _reserverRoomReservationList;

        /// <summary>
        /// Gets or sets the <see cref="RoomReservation"/> association.
        /// </summary>
        [System.Data.Linq.Mapping.Association(Name = "User_RoomReservation", Storage = "_reserverRoomReservationList", ThisKey = "Id", OtherKey = "ReserverUserID")]
        [System.Runtime.Serialization.DataMember(Order=20, EmitDefaultValue=false)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public System.Data.Linq.EntitySet<RoomReservation> ReserverRoomReservationList
        {
            get { return (serializing && !_reserverRoomReservationList.HasLoadedOrAssignedValues) ? null : _reserverRoomReservationList; }
            set { _reserverRoomReservationList.Assign(value); }
        }
        
        

        [System.Diagnostics.DebuggerNonUserCode]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private void OnReserverRoomReservationListAdd(RoomReservation entity)
        {
            SendPropertyChanging(null);
            entity.ReserverUser = this;
            SendPropertyChanged(null);
        }

        [System.Diagnostics.DebuggerNonUserCode]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private void OnReserverRoomReservationListRemove(RoomReservation entity)
        {
            SendPropertyChanging(null);
            entity.ReserverUser = null;
            SendPropertyChanged(null);
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.Data.Linq.EntitySet<RoomReservationComments> _roomReservationCommentsList;

        /// <summary>
        /// Gets or sets the <see cref="RoomReservationComments"/> association.
        /// </summary>
        [System.Data.Linq.Mapping.Association(Name = "User_RoomReservationComments", Storage = "_roomReservationCommentsList", ThisKey = "Id", OtherKey = "UserID")]
        [System.Runtime.Serialization.DataMember(Order=21, EmitDefaultValue=false)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public System.Data.Linq.EntitySet<RoomReservationComments> RoomReservationCommentsList
        {
            get { return (serializing && !_roomReservationCommentsList.HasLoadedOrAssignedValues) ? null : _roomReservationCommentsList; }
            set { _roomReservationCommentsList.Assign(value); }
        }
        
        

        [System.Diagnostics.DebuggerNonUserCode]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private void OnRoomReservationCommentsListAdd(RoomReservationComments entity)
        {
            SendPropertyChanging(null);
            entity.User = this;
            SendPropertyChanged(null);
        }

        [System.Diagnostics.DebuggerNonUserCode]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private void OnRoomReservationCommentsListRemove(RoomReservationComments entity)
        {
            SendPropertyChanging(null);
            entity.User = null;
            SendPropertyChanged(null);
        }
        #endregion

        #region Extensibility Method Definitions
        /// <summary>Called by the static constructor to add shared rules.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        static partial void AddSharedRules();
        /// <summary>Called when this instance is loaded.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnLoaded();
        /// <summary>Called when this instance is being saved.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        /// <summary>Called when this instance is created.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnCreated();
        /// <summary>Called when <see cref="Id"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnIdChanging(int value);
        /// <summary>Called after <see cref="Id"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnIdChanged();
        /// <summary>Called when <see cref="Email"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnEmailChanging(string value);
        /// <summary>Called after <see cref="Email"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnEmailChanged();
        /// <summary>Called when <see cref="IsUserAuthenticated"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnIsUserAuthenticatedChanging(Nullable<bool> value);
        /// <summary>Called after <see cref="IsUserAuthenticated"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnIsUserAuthenticatedChanged();
        /// <summary>Called when <see cref="IsAdmin"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnIsAdminChanging(bool value);
        /// <summary>Called after <see cref="IsAdmin"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnIsAdminChanged();
        /// <summary>Called when <see cref="FirstName"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnFirstNameChanging(string value);
        /// <summary>Called after <see cref="FirstName"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnFirstNameChanged();
        /// <summary>Called when <see cref="LastName"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnLastNameChanging(string value);
        /// <summary>Called after <see cref="LastName"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnLastNameChanged();
        /// <summary>Called when <see cref="PhoneNumber"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnPhoneNumberChanging(string value);
        /// <summary>Called after <see cref="PhoneNumber"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnPhoneNumberChanged();
        /// <summary>Called when <see cref="PrimaryAddress"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnPrimaryAddressChanging(string value);
        /// <summary>Called after <see cref="PrimaryAddress"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnPrimaryAddressChanged();
        /// <summary>Called when <see cref="SecondaryAddress"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnSecondaryAddressChanging(string value);
        /// <summary>Called after <see cref="SecondaryAddress"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnSecondaryAddressChanged();
        /// <summary>Called when <see cref="City"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnCityChanging(string value);
        /// <summary>Called after <see cref="City"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnCityChanged();
        /// <summary>Called when <see cref="Zip"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnZipChanging(string value);
        /// <summary>Called after <see cref="Zip"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnZipChanged();
        /// <summary>Called when <see cref="UserName"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnUserNameChanging(string value);
        /// <summary>Called after <see cref="UserName"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnUserNameChanged();
        /// <summary>Called when <see cref="Password"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnPasswordChanging(string value);
        /// <summary>Called after <see cref="Password"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnPasswordChanged();
        /// <summary>Called when <see cref="PasswordSalt"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnPasswordSaltChanging(string value);
        /// <summary>Called after <see cref="PasswordSalt"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnPasswordSaltChanged();
        /// <summary>Called when <see cref="DateCreated"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnDateCreatedChanging(Nullable<System.DateTime> value);
        /// <summary>Called after <see cref="DateCreated"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnDateCreatedChanged();
        /// <summary>Called when <see cref="ActivationGuid"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnActivationGuidChanging(Nullable<System.Guid> value);
        /// <summary>Called after <see cref="ActivationGuid"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnActivationGuidChanged();
        /// <summary>Called when <see cref="Room"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnRoomChanging(Room value);
        /// <summary>Called after <see cref="Room"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnRoomChanged();

        #endregion

        #region Serialization
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private bool serializing;

        /// <summary>
        /// Called when serializing.
        /// </summary>
        /// <param name="context">The <see cref="System.Runtime.Serialization.StreamingContext"/> for the serialization.</param>
        [System.Runtime.Serialization.OnSerializing]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public void OnSerializing(System.Runtime.Serialization.StreamingContext context) {
            serializing = true;
        }

        /// <summary>
        /// Called when serialized.
        /// </summary>
        /// <param name="context">The <see cref="System.Runtime.Serialization.StreamingContext"/> for the serialization.</param>
        [System.Runtime.Serialization.OnSerialized]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public void OnSerialized(System.Runtime.Serialization.StreamingContext context) {
            serializing = false;
        }

        /// <summary>
        /// Called when deserializing.
        /// </summary>
        /// <param name="context">The <see cref="System.Runtime.Serialization.StreamingContext"/> for the serialization.</param>
        [System.Runtime.Serialization.OnDeserializing]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public void OnDeserializing(System.Runtime.Serialization.StreamingContext context) {
            Initialize();
        }

        /// <summary>
        /// Deserializes an instance of <see cref="User"/> from XML.
        /// </summary>
        /// <param name="xml">The XML string representing a <see cref="User"/> instance.</param>
        /// <returns>An instance of <see cref="User"/> that is deserialized from the XML string.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public static User FromXml(string xml)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(User));

            using (var sr = new System.IO.StringReader(xml))
            using (var reader = System.Xml.XmlReader.Create(sr))
            {
                return deserializer.ReadObject(reader) as User;
            }
        }

        /// <summary>
        /// Deserializes an instance of <see cref="User"/> from a byte array.
        /// </summary>
        /// <param name="buffer">The byte array representing a <see cref="User"/> instance.</param>
        /// <returns>An instance of <see cref="User"/> that is deserialized from the byte array.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public static User FromBinary(byte[] buffer)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(User));

            using (var ms = new System.IO.MemoryStream(buffer))
            using (var reader = System.Xml.XmlDictionaryReader.CreateBinaryReader(ms, System.Xml.XmlDictionaryReaderQuotas.Max))
            {
                return deserializer.ReadObject(reader) as User;
            }
        }
        
        #endregion

        #region Clone
        /// <summary>
        /// Creates a new object that is a copy of the current instance.
        /// </summary>
        /// <returns>
        /// A new object that is a copy of this instance.
        /// </returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        object ICloneable.Clone()
        {
            var serializer = new System.Runtime.Serialization.DataContractSerializer(GetType());
            using (var ms = new System.IO.MemoryStream())
            {
                serializer.WriteObject(ms, this);
                ms.Position = 0;
                return serializer.ReadObject(ms);
            }
        }

        /// <summary>
        /// Creates a new object that is a copy of the current instance.
        /// </summary>
        /// <returns>
        /// A new object that is a copy of this instance.
        /// </returns>
        /// <remarks>
        /// Only loaded <see cref="T:System.Data.Linq.EntityRef`1"/> and <see cref="T:System.Data.Linq.EntitySet`1" /> child accessions will be cloned.
        /// </remarks>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public User Clone()
        {
            return (User)((ICloneable)this).Clone();
        }
        #endregion

        #region Detach Methods
        /// <summary>
        /// Detach this instance from the <see cref="System.Data.Linq.DataContext"/>.
        /// </summary>
        /// <remarks>
        /// Detaching the entity will stop all lazy loading and allow it to be added to another <see cref="System.Data.Linq.DataContext"/>.
        /// </remarks>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public override void Detach()
        {
            if (!IsAttached())
                return;

            base.Detach();
            _room = Detach(_room);
            _buildingList = Detach(_buildingList, OnBuildingListAdd, OnBuildingListRemove);
            _roomCommentsList = Detach(_roomCommentsList, OnRoomCommentsListAdd, OnRoomCommentsListRemove);
            _reserverRoomReservationList = Detach(_reserverRoomReservationList, OnReserverRoomReservationListAdd, OnReserverRoomReservationListRemove);
            _roomReservationCommentsList = Detach(_roomReservationCommentsList, OnRoomReservationCommentsListAdd, OnRoomReservationCommentsListRemove);
        }
        #endregion
    }
}
#pragma warning restore 1591
#pragma warning restore 0414

