//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

#region

using CodeSmith.Data;

#endregion

namespace Urban.Data
{
    /// <summary>
    ///     The data manager for a DataContext.
    /// </summary>
    public class UrbanDataManager : DataManagerBase<UrbanDataContext>
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref = "Urban.Data.UrbanDataManager" /> class.
        /// </summary>
        /// <param name = "context">An instance of <see cref = "Urban.Data.UrbanDataContext" /> DataContext.</param>
        public UrbanDataManager(UrbanDataContext context) : base(context)
        {
        }

        #region Managers

        private BuildingManager _buildingManager;

        private FilesManager _filesManager;
        private RoomAvailabilityManager _roomAvailabilityManager;
        private RoomCommentsManager _roomCommentsManager;
        private RoomImageLinkManager _roomImageLinkManager;
        private RoomImageTypeManager _roomImageTypeManager;

        private RoomManager _roomManager;
        private RoomReservationCommentsManager _roomReservationCommentsManager;
        private RoomReservationDatesManager _roomReservationDatesManager;
        private RoomReservationManager _roomReservationManager;
        private RoomTypeManager _roomTypeManager;
        private UserManager _userManager;

        /// <summary>
        ///     Gets the manager for Building.
        /// </summary>
        public BuildingManager Building
        {
            get
            {
                if (_buildingManager == null)
                    _buildingManager = new BuildingManager(this);

                return _buildingManager;
            }
        }

        /// <summary>
        ///     Gets the manager for Files.
        /// </summary>
        public FilesManager Files
        {
            get
            {
                if (_filesManager == null)
                    _filesManager = new FilesManager(this);

                return _filesManager;
            }
        }

        /// <summary>
        ///     Gets the manager for Room.
        /// </summary>
        public RoomManager Room
        {
            get
            {
                if (_roomManager == null)
                    _roomManager = new RoomManager(this);

                return _roomManager;
            }
        }

        /// <summary>
        ///     Gets the manager for RoomAvailability.
        /// </summary>
        public RoomAvailabilityManager RoomAvailability
        {
            get
            {
                if (_roomAvailabilityManager == null)
                    _roomAvailabilityManager = new RoomAvailabilityManager(this);

                return _roomAvailabilityManager;
            }
        }

        /// <summary>
        ///     Gets the manager for RoomComments.
        /// </summary>
        public RoomCommentsManager RoomComments
        {
            get
            {
                if (_roomCommentsManager == null)
                    _roomCommentsManager = new RoomCommentsManager(this);

                return _roomCommentsManager;
            }
        }

        /// <summary>
        ///     Gets the manager for RoomImageLink.
        /// </summary>
        public RoomImageLinkManager RoomImageLink
        {
            get
            {
                if (_roomImageLinkManager == null)
                    _roomImageLinkManager = new RoomImageLinkManager(this);

                return _roomImageLinkManager;
            }
        }

        /// <summary>
        ///     Gets the manager for RoomImageType.
        /// </summary>
        public RoomImageTypeManager RoomImageType
        {
            get
            {
                if (_roomImageTypeManager == null)
                    _roomImageTypeManager = new RoomImageTypeManager(this);

                return _roomImageTypeManager;
            }
        }

        /// <summary>
        ///     Gets the manager for RoomReservation.
        /// </summary>
        public RoomReservationManager RoomReservation
        {
            get
            {
                if (_roomReservationManager == null)
                    _roomReservationManager = new RoomReservationManager(this);

                return _roomReservationManager;
            }
        }

        /// <summary>
        ///     Gets the manager for RoomReservationComments.
        /// </summary>
        public RoomReservationCommentsManager RoomReservationComments
        {
            get
            {
                if (_roomReservationCommentsManager == null)
                    _roomReservationCommentsManager = new RoomReservationCommentsManager(this);

                return _roomReservationCommentsManager;
            }
        }

        /// <summary>
        ///     Gets the manager for RoomReservationDates.
        /// </summary>
        public RoomReservationDatesManager RoomReservationDates
        {
            get
            {
                if (_roomReservationDatesManager == null)
                    _roomReservationDatesManager = new RoomReservationDatesManager(this);

                return _roomReservationDatesManager;
            }
        }

        /// <summary>
        ///     Gets the manager for RoomType.
        /// </summary>
        public RoomTypeManager RoomType
        {
            get
            {
                if (_roomTypeManager == null)
                    _roomTypeManager = new RoomTypeManager(this);

                return _roomTypeManager;
            }
        }

        /// <summary>
        ///     Gets the manager for User.
        /// </summary>
        public UserManager User
        {
            get
            {
                if (_userManager == null)
                    _userManager = new UserManager(this);

                return _userManager;
            }
        }

        #endregion
    }
}